### ISSUE TITLE
Gradle can't find the 1.3.3

### ISSUE THREAD

**Issue by LamourBt** [SourcePointUSA/CCPA_Android_SDK#43]
Gradle is having trouble finding 

```
    implementation 'com.sourcepoint.ccpa_cmplibrary:ccpa_cmplibrary:1.3.3'
```

but I was able to download 

```
    implementation 'com.sourcepoint.ccpa_cmplibrary:ccpa_cmplibrary:1.3.2'
```

**Comment by andresilveirah** [comment]
@LamourBt thank you for reporting. For some reason our latest release wasn't published by BinTray. I've re-released and tested. You should be able to use `1.3.3` now.

**Comment by LamourBt** [comment]
I'm now able to download the new package. I will close this issue :) Thanks for your help @andresilveirah
